### ISSUE TITLE
Add ContainerSSH as CBOR user to banner

### ISSUE THREAD

**Issue by ghost** [fxamacker/images#29]
Hey there,

unfortunately there are no source files for fxamacker_cbor_banner.png that is used in fxamacker/cbor README.md, but if you'd like us we'd be happy to be on there as a CBOR user. The main repository is at https://github.com/ContainerSSH/ContainerSSH, or you can link the audit log repository that is using CBOR directly under https://github.com/ContainerSSH/auditlog.

Cheers and keep up the good work,

Janos

**Comment by fxamacker** [comment]
@janoszen Hey Janos, I think ContainerSSH is a really neat idea and project!  :+1:

@x448 when you have time, please add ContainerSSH to the animated banner.  Thanks!

**Comment by ghost** [comment]
Hey folks, I'm switching to a new GitHub account @janosdebugs, I'm hoping this issue will stay open after I delete the old account.

**Comment by ghost** [comment]
Looks like it did, I'm available here now. :)

**Comment by x448** [comment]
Closed by commit 6ac16208ca165c33b0fd50fe22a9b55f6f0b631f.

Sorry this took so long!  Emergency pulled me away from GitHub.

**Comment by ghost** [comment]
@x448 no worries, thank you very much for getting it in!
